version: "2"

services:
    app:
        build: 
            context: .
        volumes:
        - ./app:/app
        ports:
        - '8000:8000'
        working_dir: /app
        command: uvicorn api:app --host 0.0.0.0 --reload
        depends_on:
        -    db
        env_file:
            - .env
        restart: always

    db:
        image: jamielsharief/mysql:latest
        volumes:
        - .db-data:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=root
        ports:
        - "3307:3306"

    redis:
        image: redis

    nginx:
        image: nginx
        ports:
        - "8888:8888"
        volumes:
        - ./nginx/config/:/etc/nginx/conf.d/
        - ./app:/app
        depends_on:
        -    app

networks:
    default:
        
        


